# Generated by Django 2.1.1 on 2018-12-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
